package snackbar2;


import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mysql.entity.Balconista;
import mysql.entity.Item;
import mysql.entity.ItemPedido;
import mysql.entity.Mesa;
import mysql.entity.Pedido;
import mysql.entity.Tipoitem;
import mysql.util.Listas;
import mysql.util.MetodosCRUD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gaara-X
 */
public class PrincipalFrame extends javax.swing.JFrame {
    MetodosCRUD mcrud = new MetodosCRUD();
    Listas listas = new Listas();
     public ArrayList<ItemPedido> itensPedidos = new ArrayList<ItemPedido>();
    private Pedido pedido;
     public DefaultTableModel listaPedidos(){
    DefaultTableModel iP = new DefaultTableModel();
    iP.setColumnIdentifiers(new Object[] {"Item","Quantidade"});
         for(ItemPedido item:itensPedidos)
             iP.addRow(new Object[]{" "+item.getItem(),item.getQtd()});
         return iP;
    }
    private static Balconista user = new Balconista(); 
    
    
    /**
     * Creates new form NewJFrame
     */
    public PrincipalFrame(Balconista user) {
        this.user=user;
        initComponents();
        if(user.getTipousuario().getId()!=1)
        mainPN.removeTabAt(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        mainPN = new javax.swing.JTabbedPane();
        pedidosPN = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        itemsCB = new javax.swing.JComboBox();
        adicionarBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qtdTF = new javax.swing.JTextField();
        tipoItemCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        mesaLivreCB = new javax.swing.JComboBox();
        confirmarMLBT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mesaOcupadaCB = new javax.swing.JComboBox();
        desfazerBT = new javax.swing.JButton();
        confirmarMOBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosTB = new javax.swing.JTable();
        listaPedidosPN = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        pagamentoPN = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        itensPagamentoTB = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        mesasPagamentoCB = new javax.swing.JComboBox();
        valorPagarTF = new javax.swing.JTextField();
        pagarBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        trocosTF = new javax.swing.JTextField();
        gestaoPN = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pratosVendidosBT = new javax.swing.JButton();
        bebidasVendidasBT = new javax.swing.JButton();
        facturamentoBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sairMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemsCB.setModel(new javax.swing.DefaultComboBoxModel(listas.vectorItem()));
        itemsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsCBActionPerformed(evt);
            }
        });

        adicionarBT.setText("Adicionar");
        adicionarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBTActionPerformed(evt);
            }
        });

        jLabel1.setText("Itens");

        tipoItemCB.setModel(new javax.swing.DefaultComboBoxModel(listas.vectorTipoItem()));
        tipoItemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoItemCBActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de item");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(itemsCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tipoItemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qtdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(adicionarBT)))
                .addGap(123, 123, 123))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarBT)
                    .addComponent(qtdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoItemCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mesaLivreCB.setModel(new javax.swing.DefaultComboBoxModel(listas.vectorMesasLivres()));
        mesaLivreCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaLivreCBActionPerformed(evt);
            }
        });

        confirmarMLBT.setText("Confirmar");
        confirmarMLBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarMLBTActionPerformed(evt);
            }
        });

        jLabel6.setText("Mesas Livres");

        jLabel7.setText("Mesas Ocupadas");

        mesaOcupadaCB.setModel(new javax.swing.DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        mesaOcupadaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaOcupadaCBActionPerformed(evt);
            }
        });

        desfazerBT.setText("Desfazer");
        desfazerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desfazerBTActionPerformed(evt);
            }
        });

        confirmarMOBT.setText("Confirmar");
        confirmarMOBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarMOBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(confirmarMLBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmarMOBT))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesaLivreCB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(mesaOcupadaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(desfazerBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mesaOcupadaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mesaLivreCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarMLBT)
                    .addComponent(confirmarMOBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desfazerBT)
                .addGap(29, 29, 29))
        );

        pedidosTB.setModel(listaPedidos());
        jScrollPane1.setViewportView(pedidosTB);

        javax.swing.GroupLayout pedidosPNLayout = new javax.swing.GroupLayout(pedidosPN);
        pedidosPN.setLayout(pedidosPNLayout);
        pedidosPNLayout.setHorizontalGroup(
            pedidosPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pedidosPNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pedidosPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        pedidosPNLayout.setVerticalGroup(
            pedidosPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedidosPNLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPN.addTab("Pedidos", pedidosPN);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox4, 0, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout listaPedidosPNLayout = new javax.swing.GroupLayout(listaPedidosPN);
        listaPedidosPN.setLayout(listaPedidosPNLayout);
        listaPedidosPNLayout.setHorizontalGroup(
            listaPedidosPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPedidosPNLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(listaPedidosPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        listaPedidosPNLayout.setVerticalGroup(
            listaPedidosPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPedidosPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        mainPN.addTab("Lista de Pedidos", listaPedidosPN);

        itensPagamentoTB.setModel(mcrud.itensMesa(listas.listaMesas().get(0)));
        jScrollPane3.setViewportView(itensPagamentoTB);

        mesasPagamentoCB.setModel(new javax.swing.DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        mesasPagamentoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesasPagamentoCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mesasPagamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mesasPagamentoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        valorPagarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPagarTFActionPerformed(evt);
            }
        });

        pagarBT.setText("Pagar");
        pagarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarBTActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor");

        jLabel5.setText("Trocos");

        trocosTF.setEditable(false);

        javax.swing.GroupLayout pagamentoPNLayout = new javax.swing.GroupLayout(pagamentoPN);
        pagamentoPN.setLayout(pagamentoPNLayout);
        pagamentoPNLayout.setHorizontalGroup(
            pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagamentoPNLayout.createSequentialGroup()
                .addGroup(pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagamentoPNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(pagamentoPNLayout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 389, Short.MAX_VALUE))))
                    .addGroup(pagamentoPNLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorPagarTF)
                            .addComponent(trocosTF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pagarBT)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pagamentoPNLayout.setVerticalGroup(
            pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagamentoPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorPagarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagarBT)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pagamentoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(trocosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        mainPN.addTab("Pagamento", pagamentoPN);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatorios"));

        pratosVendidosBT.setText("Pratos Vendidos");
        pratosVendidosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pratosVendidosBTActionPerformed(evt);
            }
        });

        bebidasVendidasBT.setText("Bebidas Vendidas");
        bebidasVendidasBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidasVendidasBTActionPerformed(evt);
            }
        });

        facturamentoBT.setText("Facturamento");
        facturamentoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturamentoBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facturamentoBT)
                    .addComponent(bebidasVendidasBT)
                    .addComponent(pratosVendidosBT))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pratosVendidosBT)
                .addGap(44, 44, 44)
                .addComponent(bebidasVendidasBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(facturamentoBT)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gestaoPNLayout = new javax.swing.GroupLayout(gestaoPN);
        gestaoPN.setLayout(gestaoPNLayout);
        gestaoPNLayout.setHorizontalGroup(
            gestaoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestaoPNLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        gestaoPNLayout.setVerticalGroup(
            gestaoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestaoPNLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(gestaoPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        mainPN.addTab("Gestão", gestaoPN);

        jMenu1.setText("Ficheiro");

        sairMI.setText("Sair");
        sairMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMIActionPerformed(evt);
            }
        });
        jMenu1.add(sairMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPN)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPN, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBTActionPerformed
        // TODO add your handling code here:
        try{
        itensPedidos.add(new ItemPedido((Item) itemsCB.getSelectedItem(),Integer.parseInt(qtdTF.getText()),new Date()));
        pedidosTB.setModel(listaPedidos());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_adicionarBTActionPerformed

    private void confirmarMLBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarMLBTActionPerformed
        // TODO add your handling code here:
        try{
         if(itensPedidos.isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Nao tens itens na lista");
         }else{   
        System.out.println(itensPedidos); //Teste
        Mesa mesa = (Mesa) mesaLivreCB.getSelectedItem();
        mesa.setMesalivre(false); // ?? Necessita de funcao para actualizar mesas livres e ocupadas, na funcao de salvar pedido
        mcrud.salvarPedido(user, mesa, new Date()); //Criar Pedido
        for(ItemPedido iP: itensPedidos){
        iP.setPedido(listas.listaPedidos().get(listas.listaPedidos().size()-1)); //Adicionar itens ao ultimo pedido gravado
        mcrud.salvarItemPedido(iP); //Gravar itens de um pedido
        mcrud.actualizaMesas();
        mesasPagamentoCB.setModel(new DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        mesaLivreCB.setModel(new DefaultComboBoxModel(listas.vectorMesasLivres()));
        mesaOcupadaCB.setModel(new DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        itensPedidos.clear();
        pedidosTB.setModel(listaPedidos());
        }
         }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_confirmarMLBTActionPerformed

    private void mesasPagamentoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesasPagamentoCBActionPerformed
        // TODO add your handling code here:
        try{
        itensPagamentoTB.setModel(mcrud.itensMesa((Mesa) mesasPagamentoCB.getSelectedItem()));
        mcrud.total=0.0;
        itensPagamentoTB.setModel(mcrud.itensMesa((Mesa) mesasPagamentoCB.getSelectedItem()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_mesasPagamentoCBActionPerformed

    private void pagarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarBTActionPerformed
        // TODO add your handling code here:
        try{
         Double valorPagar = Double.parseDouble(valorPagarTF.getText());
         if(valorPagar<mcrud.total) //Comparar se o valor entregue é igual ou superior ao valor a ser pago
             JOptionPane.showMessageDialog(rootPane, "Valor Insuficiente");
         else{
         trocosTF.setText(String.valueOf(valorPagar-mcrud.total)); //Trocos do valor entregue pra effectuar o pagamento
         mcrud.pagarPedido((Mesa) mesasPagamentoCB.getSelectedItem()); //Metodo para confirmar o pagamento dos pedidos de uma mesa
         itensPagamentoTB.setModel(mcrud.itensMesa((Mesa) mesasPagamentoCB.getSelectedItem())); //Actualizar a lista de pedidos numa mesa
        mcrud.actualizaMesas();
        mesasPagamentoCB.setModel(new DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        mesaLivreCB.setModel(new DefaultComboBoxModel(listas.vectorMesasLivres()));
        mesaOcupadaCB.setModel(new DefaultComboBoxModel(listas.vectorMesasOcupadas()));
         }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
       
    }//GEN-LAST:event_pagarBTActionPerformed

    private void valorPagarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPagarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPagarTFActionPerformed

    private void mesaLivreCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaLivreCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesaLivreCBActionPerformed

    private void tipoItemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoItemCBActionPerformed
        // TODO add your handling code here:
        try{
        //Filtrar lista de item por tipo de item    
        itemsCB.setModel(new DefaultComboBoxModel(listas.vectorItems((Tipoitem) tipoItemCB.getSelectedItem())));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_tipoItemCBActionPerformed

    private void desfazerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desfazerBTActionPerformed
        // TODO add your handling code here:
        //Desfazer a ultima lista de de itens a um pedido
        try{
        itensPedidos.remove(itensPedidos.size()-1);
        pedidosTB.setModel(listaPedidos());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_desfazerBTActionPerformed

    private void itemsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsCBActionPerformed

    private void confirmarMOBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarMOBTActionPerformed
        // TODO add your handling code here:
        try{
        if(itensPedidos.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Nao tens itens na lista");
        }else{    
        System.out.println(itensPedidos); //Teste
        Mesa mesa = (Mesa) mesaOcupadaCB.getSelectedItem();
        mesa.setMesalivre(false); // ?? Necessita de funcao para actualizar mesas livres e ocupadas, na funcao de salvar pedido
        mcrud.salvarPedido(user, mesa, new Date()); //Criar Pedido
        for(ItemPedido iP: itensPedidos){
        iP.setPedido(listas.listaPedidos().get(listas.listaPedidos().size()-1)); //Adicionar itens ao ultimo pedido gravado
        mcrud.salvarItemPedido(iP); //Gravar itens de um pedido
        mcrud.actualizaMesas();
        mesasPagamentoCB.setModel(new DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        mesaLivreCB.setModel(new DefaultComboBoxModel(listas.vectorMesasLivres()));
        mesaOcupadaCB.setModel(new DefaultComboBoxModel(listas.vectorMesasOcupadas()));
        itensPedidos.clear();
        pedidosTB.setModel(listaPedidos());
        }
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_confirmarMOBTActionPerformed

    private void mesaOcupadaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesaOcupadaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesaOcupadaCBActionPerformed

    private void pratosVendidosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pratosVendidosBTActionPerformed
        // TODO add your handling code here:
        new PratoReport().setVisible(true);
    }//GEN-LAST:event_pratosVendidosBTActionPerformed

    private void bebidasVendidasBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidasVendidasBTActionPerformed
        // TODO add your handling code here:
        new BebidaReport().setVisible(true);
    }//GEN-LAST:event_bebidasVendidasBTActionPerformed

    private void facturamentoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturamentoBTActionPerformed
        // TODO add your handling code here:
        new FacturamentoReport().setVisible(true);
    }//GEN-LAST:event_facturamentoBTActionPerformed

    private void sairMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMIActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_sairMIActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame(user).setVisible(true);
            }
        });
    }
   
    
    //lista de pedidos na tabela
   
    //Criar lista de itens de pedidos, associar a um pedido guardado na base de dados apos confirmar pedido
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBT;
    private javax.swing.JButton bebidasVendidasBT;
    private javax.swing.JButton confirmarMLBT;
    private javax.swing.JButton confirmarMOBT;
    private javax.swing.JButton desfazerBT;
    private javax.swing.JButton facturamentoBT;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel gestaoPN;
    private javax.swing.JComboBox itemsCB;
    private javax.swing.JTable itensPagamentoTB;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel listaPedidosPN;
    private javax.swing.JTabbedPane mainPN;
    private javax.swing.JComboBox mesaLivreCB;
    private javax.swing.JComboBox mesaOcupadaCB;
    private javax.swing.JComboBox mesasPagamentoCB;
    private javax.swing.JPanel pagamentoPN;
    private javax.swing.JButton pagarBT;
    private javax.swing.JPanel pedidosPN;
    private javax.swing.JTable pedidosTB;
    private javax.swing.JButton pratosVendidosBT;
    private javax.swing.JTextField qtdTF;
    private javax.swing.JMenuItem sairMI;
    private javax.swing.JComboBox tipoItemCB;
    private javax.swing.JTextField trocosTF;
    private javax.swing.JTextField valorPagarTF;
    // End of variables declaration//GEN-END:variables
}

