package mysql.entity;
// Generated May 24, 2016 4:04:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Balconista generated by hbm2java
 */
public class Balconista  implements java.io.Serializable {


     private Integer id;
     private Tipousuario tipousuario;
     private String nome;
     private Date dataNascimento;
     private String morada;
     private int nuit;
     private String username;
     private String password;
     private boolean activo;
     private Set pedidos = new HashSet(0);

    public Balconista() {
    }

	
    public Balconista(Tipousuario tipousuario, String nome, Date dataNascimento, int nuit, String username, String password, boolean activo) {
        this.tipousuario = tipousuario;
        this.nome = nome;
        this.dataNascimento = dataNascimento;
        this.nuit = nuit;
        this.username = username;
        this.password = password;
        this.activo = activo;
    }
    public Balconista(Tipousuario tipousuario, String nome, Date dataNascimento, String morada, int nuit, String username, String password, boolean activo, Set pedidos) {
       this.tipousuario = tipousuario;
       this.nome = nome;
       this.dataNascimento = dataNascimento;
       this.morada = morada;
       this.nuit = nuit;
       this.username = username;
       this.password = password;
       this.activo = activo;
       this.pedidos = pedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getNuit() {
        return this.nuit;
    }
    
    public void setNuit(int nuit) {
        this.nuit = nuit;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


