package mysql.entity;
// Generated May 27, 2016 1:50:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ItemPedido generated by hbm2java
 */
public class ItemPedido  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private Pedido pedido;
     private int qtd;
     private Date data;

    public ItemPedido() {
    }

    public ItemPedido(Item item, Pedido pedido, int qtd, Date data) {
       this.item = item;
       this.pedido = pedido;
       this.qtd = qtd;
       this.data = data;
    }
   
    public ItemPedido(Item item, int qtd, Date data) {
       this.item = item;
       this.qtd = qtd;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public int getQtd() {
        return this.qtd;
    }
    
    public void setQtd(int qtd) {
        this.qtd = qtd;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    public String toString(){
        return "Item:"+item+" Quantidade:"+qtd+" Data:"+data;
    }



}


