package mysql.entity;
// Generated May 27, 2016 1:50:42 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Logs generated by hbm2java
 */
public class Logs  implements java.io.Serializable {


     private Integer id;
     private Balconista balconista;
     private String accao;
     private Date data;

    public Logs() {
    }

    public Logs(Balconista balconista, String accao, Date data) {
       this.balconista = balconista;
       this.accao = accao;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balconista getBalconista() {
        return this.balconista;
    }
    
    public void setBalconista(Balconista balconista) {
        this.balconista = balconista;
    }
    public String getAccao() {
        return this.accao;
    }
    
    public void setAccao(String accao) {
        this.accao = accao;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


