package mysql.entity;
// Generated May 27, 2016 1:50:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Mesa generated by hbm2java
 */
public class Mesa  implements java.io.Serializable {


     private Integer id;
     private int numero;
     private boolean mesalivre;
     private boolean activa;
     private Set pedidos = new HashSet(0);

    public Mesa() {
    }

	
    public Mesa(int numero, boolean mesalivre, boolean activa) {
        this.numero = numero;
        this.mesalivre = mesalivre;
        this.activa = activa;
    }
    public Mesa(int numero, boolean mesalivre, boolean activa, Set pedidos) {
       this.numero = numero;
       this.mesalivre = mesalivre;
       this.activa = activa;
       this.pedidos = pedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public boolean isMesalivre() {
        return this.mesalivre;
    }
    
    public void setMesalivre(boolean mesalivre) {
        this.mesalivre = mesalivre;
    }
    public boolean isActiva() {
        return this.activa;
    }
    
    public void setActiva(boolean activa) {
        this.activa = activa;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

    public String toString(){
        return "Mesa "+numero;
    }



}


