package mysql.entity;
// Generated May 27, 2016 1:50:42 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Balconista balconista;
     private Mesa mesa;
     private boolean pago;
     private Date data;
     private Set itemPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Balconista balconista, Mesa mesa, boolean pago, Date data) {
        this.balconista = balconista;
        this.mesa = mesa;
        this.pago = pago;
        this.data = data;
    }
    
     public Pedido(Balconista balconista, Mesa mesa, Date data) {
        this.balconista = balconista;
        this.mesa = mesa;
        this.data = data;
    }
    
    public Pedido(Balconista balconista, Mesa mesa, boolean pago, Date data, Set itemPedidos) {
       this.balconista = balconista;
       this.mesa = mesa;
       this.pago = pago;
       this.data = data;
       this.itemPedidos = itemPedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Balconista getBalconista() {
        return this.balconista;
    }
    
    public void setBalconista(Balconista balconista) {
        this.balconista = balconista;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public boolean isPago() {
        return this.pago;
    }
    
    public void setPago(boolean pago) {
        this.pago = pago;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getItemPedidos() {
        return this.itemPedidos;
    }
    
    public void setItemPedidos(Set itemPedidos) {
        this.itemPedidos = itemPedidos;
    }




}


