package mysql.entity;
// Generated May 24, 2016 4:04:14 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Integer id;
     private String designacao;
     private Set balconistas = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String designacao) {
        this.designacao = designacao;
    }
    public Tipousuario(String designacao, Set balconistas) {
       this.designacao = designacao;
       this.balconistas = balconistas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }
    public Set getBalconistas() {
        return this.balconistas;
    }
    
    public void setBalconistas(Set balconistas) {
        this.balconistas = balconistas;
    }

    public String toString(){
        return designacao;
    }



}


